extends AttributeOld
class_name AttributeF

enum TYPE {
	RUN_MAX_SPEED,
	RUN_ACCELERATION,
	GROUND_STOP_FRICTION,
	JUMP_IMPULSE,
	MAX_JUMP_VELOCITY,
	AIR_ACCELERATION,
	AIR_CONTROL_MAX_VELOCITY,
	AIR_FRICTION,
	CONSTANT_SLIDE_FRICTION,
	FORCE_SLIDE_SLOPE_ANGLE,
	GRAPPLING_HOOK_RANGE,
	GRAPPLING_HOOK_SPEED
}

@export var type: TYPE
@export var value: float

func get_value() -> float:
	return value
